FROM python:3.7-alpine
ENV PYTHONUNBUFFERED 1
COPY joplin-web-master/requirements.txt /app/
COPY joplin-web-master/joplin_web       /app/
WORKDIR /app
RUN apk add --no-cache --virtual .build-deps gcc musl-dev alpine-sdk \
  && pip install -U setuptools pip \
  && pip install --no-cache-dir -r requirements.txt \
  && apk del .build-deps gcc musl-dev alpine-sdk
CMD ["python", "/app/app.py"]
