# If need be - updating:
#   docker-compose down -v # Remove everything
#   docker-compose pull    # Updates images
#   docker-compose build --no-cache --pull --force-rm  # Rebuild local Dockerfile
#   docker-compose up -d   # Start container

version: '3.4'

services:
  web:
    build: .
    image: joplin-web:latest
    container_name: joplin-web
    ports:
      # Point your browser to http://localhost:8001 to access Joplin Web
      - 127.0.0.1:8001:8001
    volumes:
      # The first parameter is existing path to a copy of Joplin Desktop profile
      - /var/lib/docker-vol/joplin_profile:/joplin-desktop
    environment:
      - JW_DEBUG=False
      - JW_PAGINATOR=20
      #- JW_HTTP_PORT=8001 # Not needed thanks to port mapping above
      # See Joplin Desktop App:
      # // Tools // Web clipper options: Authorization token
      - JOPLIN_WEBCLIPPER_TOKEN=0b1c579cb0bxf0d35b3ef799f6065f5706fe9b4de60781368a7070c64d55e0dec2ccc4566c36768f7203cd0ed5b39b9f13828f0f2bff1faa327637a4eee75c90
      - JOPLIN_RESOURCES=/joplin-desktop/resources
    #command: /bin/sh -c 'while true; do echo "Staying Alive!"; sleep 60; done'
